# _config.yml

title: Research Title
description: An accompanying website for a research paper.

baseurl: ""
url: "https://example.com"

conference:
  name: Conference Name
  year: 2026

content:
  footer: Darth Vader
  affiliation:
    name: Death Star
    department: The Empire
    url: https://www.starwars.com/databank/death-star
  type: Paper
  authors:
    - name: Darth Vader
      url: https://www.starwars.com/databank/darth-vader
    - name: Emperor Palpatine
      url: https://www.starwars.com/databank/emperor-palpatine
  links:
    - label: Paper Link
      url: https://doi.org/10.1145/XXXXXXX.XXXXXXX

permalink: pretty
